// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMyHelloMessage struct {
	TargetCat            string   `protobuf:"bytes,1,opt,name=target_cat,json=targetCat,proto3" json:"target_cat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyHelloMessage) Reset()         { *m = GetMyHelloMessage{} }
func (m *GetMyHelloMessage) String() string { return proto.CompactTextString(m) }
func (*GetMyHelloMessage) ProtoMessage()    {}
func (*GetMyHelloMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_570ecb6ce8ff421a, []int{0}
}
func (m *GetMyHelloMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyHelloMessage.Unmarshal(m, b)
}
func (m *GetMyHelloMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyHelloMessage.Marshal(b, m, deterministic)
}
func (dst *GetMyHelloMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyHelloMessage.Merge(dst, src)
}
func (m *GetMyHelloMessage) XXX_Size() int {
	return xxx_messageInfo_GetMyHelloMessage.Size(m)
}
func (m *GetMyHelloMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyHelloMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyHelloMessage proto.InternalMessageInfo

func (m *GetMyHelloMessage) GetTargetCat() string {
	if m != nil {
		return m.TargetCat
	}
	return ""
}

type MyHelloResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyHelloResponse) Reset()         { *m = MyHelloResponse{} }
func (m *MyHelloResponse) String() string { return proto.CompactTextString(m) }
func (*MyHelloResponse) ProtoMessage()    {}
func (*MyHelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_570ecb6ce8ff421a, []int{1}
}
func (m *MyHelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyHelloResponse.Unmarshal(m, b)
}
func (m *MyHelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyHelloResponse.Marshal(b, m, deterministic)
}
func (dst *MyHelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyHelloResponse.Merge(dst, src)
}
func (m *MyHelloResponse) XXX_Size() int {
	return xxx_messageInfo_MyHelloResponse.Size(m)
}
func (m *MyHelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MyHelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MyHelloResponse proto.InternalMessageInfo

func (m *MyHelloResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyHelloResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMyHelloMessage)(nil), "GetMyHelloMessage")
	proto.RegisterType((*MyHelloResponse)(nil), "MyHelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	GetMyHello(ctx context.Context, in *GetMyHelloMessage, opts ...grpc.CallOption) (*MyHelloResponse, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) GetMyHello(ctx context.Context, in *GetMyHelloMessage, opts ...grpc.CallOption) (*MyHelloResponse, error) {
	out := new(MyHelloResponse)
	err := c.cc.Invoke(ctx, "/Hello/GetMyHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	GetMyHello(context.Context, *GetMyHelloMessage) (*MyHelloResponse, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_GetMyHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyHelloMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).GetMyHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hello/GetMyHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).GetMyHello(ctx, req.(*GetMyHelloMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyHello",
			Handler:    _Hello_GetMyHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_hello_570ecb6ce8ff421a) }

var fileDescriptor_hello_570ecb6ce8ff421a = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe2, 0x12, 0x74, 0x4f, 0x2d, 0xf1, 0xad,
	0xf4, 0x00, 0x89, 0xf9, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0xc9, 0x72, 0x71, 0x95, 0x24,
	0x16, 0xa5, 0xa7, 0x96, 0xc4, 0x27, 0x27, 0x96, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71,
	0x42, 0x44, 0x9c, 0x13, 0x4b, 0x94, 0x2c, 0xb9, 0xf8, 0xa1, 0x1a, 0x82, 0x52, 0x8b, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0xa1, 0x6a, 0xc1, 0x6c, 0x90,
	0x58, 0x76, 0x66, 0x5e, 0x8a, 0x04, 0x13, 0x44, 0x0c, 0xc4, 0x36, 0xb2, 0xe5, 0x62, 0x05, 0x6b,
	0x14, 0x32, 0xe1, 0xe2, 0x42, 0xd8, 0x2b, 0x24, 0xa4, 0x87, 0xe1, 0x08, 0x29, 0x01, 0x3d, 0x34,
	0x4b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x8e, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x20, 0xe3,
	0x2d, 0x9b, 0xc3, 0x00, 0x00, 0x00,
}
